### ISSUE TITLE
memory look some nervous

### ISSUE THREAD

**Issue by HotWordland** [zixun/CocoaChinaPlus#10]
I browse some article and memory increase so fast 

![01](https://cloud.githubusercontent.com/assets/6984865/11689369/8fdbc68a-9ecc-11e5-956d-f0764b31819b.jpg)

![02](https://cloud.githubusercontent.com/assets/6984865/11689175/a1db2b92-9ecb-11e5-8110-04979af8d76a.jpg)

**Comment by zixun** [comment]
hi @HotWordland ,it looks like the article view controller is not dealloc while back to the list view controller, I will take part in it tonight

**Comment by DaidoujiChen** [comment]
Hello @zixun,

恕我使用中文...
![2015-12-10 11 21 06](https://cloud.githubusercontent.com/assets/670441/11706060/5c27a728-9f30-11e5-9a76-60a45fc6acc0.png)
看了一下, root cause 應該是 `CCPArticleViewController` 裡面的 `CCCocoaChinaWebView` 一直沒有被釋放. 可能再要看一下 `CCCocoaChinaWebView` 為什麼在這個地方不會被釋放. 如果單純的把他放在 `AppDelegate` 建立的話

```
CCCocoaChinaWebView(frame: UIScreen.mainScreen().bounds)
```

倒是可以正常的調用到 `deinit`

**Comment by zixun** [comment]
@DaidoujiChen 谢谢。我找到原因了，是因为CCPArticleViewController 里的ZXCuteView循环引用导致的，已经更新ZXKit,[https://github.com/zixun/ZXKit/commit/1eec9fc3bac567dcb1466a264704f7b5dc6b3088](https://github.com/zixun/ZXKit/commit/1eec9fc3bac567dcb1466a264704f7b5dc6b3088)

**Comment by zixun** [comment]
@HotWordland thx for you issues,it is fixed.and you can run 'pod update ' or 'pod install',it will download the newest ZXKit code

**Comment by DaidoujiChen** [comment]
:+1:
